version: "3.9"

services:

  django:
    build: 
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/service 
    command:
      - bash
      - -c
      - "python manage.py runserver 0.0.0.0:8000 --noreload"

  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_HOST: 'db'
      MYSQL_DATABASE: 'mysql'
      MYSQL_PASSWORD: 'mysql'
    ports:

    volumes:
      - db:/var/lib/mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    hostname: redis
    expose: 
      - '6379'

  celery:
    build:
      context: .
    hostname: celery
    command: python -m celery -A core worker -l info
    expose:
     - '5672'
    depends_on:
      - db
      - redis
    volumes:
      - .:/service

volumes:
  db:


