FROM python:3.10

WORKDIR /service

COPY . /service/

RUN pip3 install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV NAME World

CMD ["celery", "-A", "core", "worker", "--loglevel=info"]